"""

Golden pins for the layout consumers outside the derivative assembly.

`test_nlp_hessian_golden.py` pins the five NLP callbacks and both structures. The NLP
layout -- where each problem variable and constraint sits in the flat decision-variable
and constraint vectors under each spectral method -- is also read by the code that
builds the NLP bounds, the scaling vectors, and the initial point, and by the code that
maps Ipopt's result back into a `Solution`. These tests pin all four, for the same
problems and meshes as the NLP golden tests, so a change to how the layout is derived
cannot move a value without failing here.

Bounds are pinned twice: with each example's own bounds, which reach the infinite-bound
paths, and with distinct finite values on every bound, so that a value read from or
written to the wrong index cannot coincide with the right one. Scaling uses distinct
factors for the same reason. The `Solution` is built from deterministic synthetic Ipopt
output, not from a solve.

The pinned values were generated by the implementation that predates the layout
refactor. To add cases after an *intentional* extension:

    python tests/modules/test_layout_golden.py

which adds missing cases and keeps existing ones (``--all`` overwrites everything, only for
an intentional behavior change). Never regenerate to make a refactor pass.

"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

import numpy as np
import pytest
from test_nlp_hessian_golden import MESHES, PROBLEMS, SPECTRAL_METHODS

from yapss._private.auto import make_auto_functions
from yapss._private.bounds import (
    get_nlp_constraint_function_bounds,
    get_nlp_decision_variable_bounds,
)
from yapss._private.guess import make_initial_guess_nlp
from yapss._private.mesh import Mesh
from yapss._private.nlp import NLP
from yapss._private.solution import make_solution_object
from yapss._private.solver import get_nlp_scaling

GOLDEN_PATH = Path(__file__).parent / "data" / "layout_golden.json"

CASES = [
    (name, spectral)
    for name in PROBLEMS
    for spectral in (SPECTRAL_METHODS if MESHES[name] else ("lgl",))
]

# Values produced by plain arithmetic and indexing; the Solution's continuous-function
# fields (dynamics, integrand, path, Hamiltonian) go through CasADi, like the NLP golden
# tests' exact-derivative values, and use the same tolerance.
RTOL = 1e-10
ATOL = 1e-12


def build_problem(name: str, spectral_method: str) -> Any:
    problem = PROBLEMS[name].setup()
    for p, points in enumerate(MESHES[name]):
        problem.mesh.phase[p].collocation_points = points
        problem.mesh.phase[p].fraction = [1.0 / len(points)] * len(points)
    problem.spectral_method = spectral_method
    problem.derivatives.method = "auto"
    problem.derivatives.order = "second"
    return problem


def set_distinct_bounds(problem: Any) -> None:
    """Give every bound a finite value no other bound shares.

    The initial and final state bounds are tighter than the state bounds on alternate
    components, so the intersection the NLP bounds take is exercised in both directions.
    """
    counter = iter(range(1, 100_000))

    def distinct(n: int, base: float) -> tuple[np.ndarray, np.ndarray]:
        offsets = np.array([next(counter) for _ in range(n)], dtype=float) * 0.37
        return -(base + offsets), base + offsets + 0.25

    for p, phase in enumerate(problem.bounds.phase):
        phase.initial_time.lower, phase.initial_time.upper = 0.01 * p, 0.1 + 0.01 * p
        phase.final_time.lower, phase.final_time.upper = 1.0 + p, 2.0 + p
        phase.duration.lower, phase.duration.upper = 0.5 + 0.01 * p, 3.0 + p
        nx = problem.nx[p]
        phase.state.lower, phase.state.upper = distinct(nx, 10.0)
        for boundary, base in ((phase.initial_state, 5.0), (phase.final_state, 7.0)):
            lower, upper = distinct(nx, base)
            loose = np.arange(nx) % 2 == 1
            lower[loose] -= 20.0
            upper[loose] += 20.0
            boundary.lower, boundary.upper = lower, upper
        phase.control.lower, phase.control.upper = distinct(problem.nu[p], 3.0)
        phase.integral.lower, phase.integral.upper = distinct(problem.nq[p], 4.0)
        phase.path.lower, phase.path.upper = distinct(problem.nh[p], 6.0)
    problem.bounds.parameter.lower, problem.bounds.parameter.upper = distinct(problem.ns, 8.0)
    problem.bounds.discrete.lower, problem.bounds.discrete.upper = distinct(problem.nd, 9.0)


def set_distinct_scales(problem: Any) -> None:
    """Give every scale factor a positive value no other factor shares."""
    counter = iter(range(1, 100_000))

    def distinct(n: int) -> np.ndarray:
        return 1.0 + 0.13 * np.array([next(counter) for _ in range(n)], dtype=float)

    problem.scale.objective = 2.5
    for p, phase in enumerate(problem.scale.phase):
        phase.time = float(distinct(1)[0])
        phase.state = distinct(problem.nx[p])
        phase.control = distinct(problem.nu[p])
        phase.integral = distinct(problem.nq[p])
        phase.dynamics = distinct(problem.nx[p])
        phase.path = distinct(problem.nh[p])
    problem.scale.parameter = distinct(problem.ns)
    problem.scale.discrete = distinct(problem.nd)


def bounds_fields(problem: Any) -> dict[str, list[float]]:
    ub, lb = get_nlp_decision_variable_bounds(problem)
    gu, gl = get_nlp_constraint_function_bounds(problem)
    return {"lb": lb.tolist(), "ub": ub.tolist(), "gl": gl.tolist(), "gu": gu.tolist()}


def solution_fields(problem: Any) -> dict[str, Any]:
    """Build a Solution from deterministic synthetic Ipopt output and flatten its arrays."""
    mesh = Mesh(problem.mesh.phase)
    mesh.set_matrices(problem.spectral_method)
    z0 = make_initial_guess_nlp(problem, mesh)
    nlp = NLP(problem, make_auto_functions(problem), mesh)
    nz = len(z0)
    x = z0 + 0.01 * np.sin(1.0 + np.arange(nz))
    g = np.asarray(nlp.constraints(x), dtype=float)
    nc = len(g)
    nlp_info = {
        "x": x,
        "g": g,
        "obj_val": float(nlp.objective(x)),
        "mult_g": 0.5 + 0.3 * np.cos(1.0 + np.arange(nc)),
        "mult_x_L": 0.2 + 0.1 * np.sin(2.0 + np.arange(nz)) ** 2,
        "mult_x_U": 0.3 + 0.1 * np.cos(3.0 + np.arange(nz)) ** 2,
        "status": 0,
    }
    solution = make_solution_object(problem, mesh, nlp, nlp_info)

    def flat(value: Any) -> Any:
        return np.asarray(value, dtype=float).tolist()

    fields: dict[str, Any] = {
        name: flat(getattr(solution, name))
        for name in ("objective", "parameter", "parameter_multiplier", "discrete")
    }
    fields["discrete_multiplier"] = flat(solution.discrete_multiplier)
    phase_names = (
        "time",
        "time_c",
        "state",
        "control",
        "costate",
        "control_multiplier",
        "path_multiplier",
        "integral_multiplier",
        "hamiltonian",
        "dynamics",
        "integrand",
        "path",
        "integral",
        "initial_time",
        "final_time",
        "duration",
        "initial_state",
        "final_state",
        "initial_time_multiplier",
        "final_time_multiplier",
        "duration_multiplier",
    )
    for p, phase in enumerate(solution.phase):
        for name in phase_names:
            fields[f"phase{p}.{name}"] = flat(getattr(phase, name))
    return fields


def evaluate_case(name: str, spectral_method: str) -> dict[str, Any]:
    """Return every pinned layout quantity for one case, as plain lists."""
    example = build_problem(name, spectral_method)
    distinct = build_problem(name, spectral_method)
    set_distinct_bounds(distinct)
    scaled = build_problem(name, spectral_method)
    set_distinct_scales(scaled)

    mesh = Mesh(example.mesh.phase)
    mesh.set_matrices(example.spectral_method)
    obj_scale, z_scaling, c_scaling = get_nlp_scaling(scaled)
    return {
        "example_bounds": bounds_fields(example),
        "distinct_bounds": bounds_fields(distinct),
        "scaling": {
            "objective": [float(obj_scale)],
            "z": np.asarray(z_scaling).tolist(),
            "c": np.asarray(c_scaling).tolist(),
        },
        "z0": {"z0": make_initial_guess_nlp(example, mesh).tolist()},
        "solution": solution_fields(example),
    }


def case_key(name: str, spectral_method: str) -> str:
    return f"{name}/{spectral_method}"


@pytest.fixture(scope="module")
def golden() -> dict:
    if not GOLDEN_PATH.exists():  # pragma: no cover
        pytest.fail(f"golden file missing; generate it with: python {__file__}")
    return json.loads(GOLDEN_PATH.read_text())


@pytest.mark.parametrize(("name", "spectral_method"), CASES)
@pytest.mark.parametrize(
    "group", ["example_bounds", "distinct_bounds", "scaling", "z0", "solution"]
)
def test_layout_consumers_match_golden(name, spectral_method, group, golden):
    """Bounds, scaling, initial point, and Solution mapping are unchanged from the pins."""
    expected = golden[case_key(name, spectral_method)][group]
    actual = evaluate_case(name, spectral_method)[group]
    assert actual.keys() == expected.keys()
    for field, expected_values in expected.items():
        np.testing.assert_allclose(
            np.asarray(actual[field], dtype=float),
            np.asarray(expected_values, dtype=float),
            rtol=RTOL,
            atol=ATOL,
            err_msg=f"{group}.{field} changed for {case_key(name, spectral_method)}",
        )


def main(regenerate_all: bool = False) -> None:
    """Add missing cases to the golden file; keep the existing pinned values."""
    data: dict = {}
    if GOLDEN_PATH.exists() and not regenerate_all:
        data = json.loads(GOLDEN_PATH.read_text())
    added = 0
    for case in CASES:
        key = case_key(*case)
        if key not in data:
            data[key] = evaluate_case(*case)
            added += 1
    GOLDEN_PATH.parent.mkdir(parents=True, exist_ok=True)
    GOLDEN_PATH.write_text(json.dumps(data, indent=1))
    print(f"wrote {GOLDEN_PATH} ({len(data)} cases, {added} added)")


if __name__ == "__main__":
    main(regenerate_all="--all" in sys.argv)
