"""

What Ipopt documents about each of its options: kind, range, allowed settings.

Generated by ``utils/get_ipopt_options.py`` from Ipopt's ``doc/options.dox``. Do not
edit by hand.

This table never decides whether Ipopt accepts an option: that depends on the build,
which need not match the documentation this was scraped from, so Ipopt stays the
authority. YAPSS reads an option's kind, to check the type of a value where it is
assigned, and its name, to add a hint when Ipopt refuses it (see
``ipopt_options.refusal_message``). The ranges and settings are kept as reference;
nothing reads them.

Scraped from Ipopt 3.14.20 (``releases/3.14.20``) on 2026-09-25.
"""

from __future__ import annotations

IPOPT_DOC_VERSION = "3.14.20"
"""The Ipopt release whose documentation this table describes.

The Ipopt library actually loaded may be a different version.
"""

IpoptOptionSpec = dict[str, str | float | bool | tuple[str, ...]]
"""Kind, and either a numeric range or the allowed string values."""

IPOPT_OPTION_SPECS: dict[str, IpoptOptionSpec] = {
    "accept_after_max_steps": {"kind": "int", "low": -1.0, "low_inclusive": True},
    "accept_every_trial_step": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "acceptable_compl_inf_tol": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "acceptable_constr_viol_tol": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "acceptable_dual_inf_tol": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "acceptable_iter": {"kind": "int", "low": 0.0, "low_inclusive": True},
    "acceptable_obj_change_tol": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "acceptable_tol": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "adaptive_mu_globalization": {
        "kind": "str",
        "values": (
            "kkt-error",
            "obj-constr-filter",
            "never-monotone-mode",
        ),
    },
    "adaptive_mu_kkt_norm_type": {
        "kind": "str",
        "values": (
            "1-norm",
            "2-norm-squared",
            "max-norm",
            "2-norm",
        ),
    },
    "adaptive_mu_kkterror_red_fact": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 1.0,
        "high_inclusive": False,
    },
    "adaptive_mu_kkterror_red_iters": {"kind": "int", "low": 0.0, "low_inclusive": True},
    "adaptive_mu_monotone_init_factor": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "adaptive_mu_restore_previous_iterate": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "alpha_for_y": {
        "kind": "str",
        "values": (
            "primal",
            "bound-mult",
            "min",
            "max",
            "full",
            "min-dual-infeas",
            "safer-min-dual-infeas",
            "primal-and-full",
            "dual-and-full",
            "acceptor",
        ),
    },
    "alpha_for_y_tol": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "alpha_min_frac": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 1.0,
        "high_inclusive": False,
    },
    "alpha_red_factor": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 1.0,
        "high_inclusive": False,
    },
    "barrier_tol_factor": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "bound_frac": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 0.5,
        "high_inclusive": True,
    },
    "bound_mult_init_method": {
        "kind": "str",
        "values": (
            "constant",
            "mu-based",
        ),
    },
    "bound_mult_init_val": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "bound_mult_reset_threshold": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "bound_push": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "bound_relax_factor": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "check_derivatives_for_naninf": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "compl_inf_tol": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "constr_mult_init_max": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "constr_mult_reset_threshold": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "constr_viol_tol": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "constraint_violation_norm_type": {
        "kind": "str",
        "values": (
            "1-norm",
            "2-norm",
            "max-norm",
        ),
    },
    "corrector_compl_avrg_red_fact": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "corrector_type": {
        "kind": "str",
        "values": (
            "none",
            "affine",
            "primal-dual",
        ),
    },
    "delta": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "dependency_detection_with_rhs": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "dependency_detector": {
        "kind": "str",
        "values": (
            "none",
            "mumps",
            "wsmp",
            "ma28",
        ),
    },
    "derivative_test": {
        "kind": "str",
        "values": (
            "none",
            "first-order",
            "second-order",
            "only-second-order",
        ),
    },
    "derivative_test_first_index": {"kind": "int", "low": -2.0, "low_inclusive": True},
    "derivative_test_perturbation": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "derivative_test_print_all": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "derivative_test_tol": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "diverging_iterates_tol": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "dual_inf_tol": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "eta_phi": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 0.5,
        "high_inclusive": False,
    },
    "evaluate_orig_obj_at_resto_trial": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "expect_infeasible_problem": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "expect_infeasible_problem_ctol": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "expect_infeasible_problem_ytol": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "fast_step_computation": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "file_append": {
        "kind": "str",
        "file_only": True,
        "values": (
            "yes",
            "no",
        ),
    },
    "file_print_level": {
        "kind": "int",
        "file_only": True,
        "low": 0.0,
        "low_inclusive": True,
        "high": 12.0,
        "high_inclusive": True,
    },
    "filter_margin_fact": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 1.0,
        "high_inclusive": False,
    },
    "filter_max_margin": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "filter_reset_trigger": {"kind": "int", "low": 1.0, "low_inclusive": True},
    "findiff_perturbation": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "first_hessian_perturbation": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "fixed_mu_oracle": {
        "kind": "str",
        "values": (
            "probing",
            "loqo",
            "quality-function",
            "average_compl",
        ),
    },
    "fixed_variable_treatment": {
        "kind": "str",
        "values": (
            "make_parameter",
            "make_parameter_nodual",
            "make_constraint",
            "relax_bounds",
        ),
    },
    "gamma_phi": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 1.0,
        "high_inclusive": False,
    },
    "gamma_theta": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 1.0,
        "high_inclusive": False,
    },
    "grad_f_constant": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "gradient_approximation": {
        "kind": "str",
        "values": (
            "exact",
            "finite-difference-values",
        ),
    },
    "hessian_approximation": {
        "kind": "str",
        "values": (
            "exact",
            "limited-memory",
        ),
    },
    "hessian_approximation_space": {
        "kind": "str",
        "values": (
            "nonlinear-variables",
            "all-variables",
        ),
    },
    "hessian_constant": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "honor_original_bounds": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "hsllib": {"kind": "str"},
    "inf_pr_output": {
        "kind": "str",
        "values": (
            "internal",
            "original",
        ),
    },
    "jac_c_constant": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "jac_d_constant": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "jacobian_approximation": {
        "kind": "str",
        "values": (
            "exact",
            "finite-difference-values",
        ),
    },
    "jacobian_regularization_exponent": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "jacobian_regularization_value": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "kappa_d": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "kappa_sigma": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "kappa_soc": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "least_square_init_duals": {
        "kind": "str",
        "values": (
            "no",
            "yes",
        ),
    },
    "least_square_init_primal": {
        "kind": "str",
        "values": (
            "no",
            "yes",
        ),
    },
    "limited_memory_aug_solver": {
        "kind": "str",
        "values": (
            "sherman-morrison",
            "extended",
        ),
    },
    "limited_memory_init_val": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "limited_memory_init_val_max": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "limited_memory_init_val_min": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "limited_memory_initialization": {
        "kind": "str",
        "values": (
            "scalar1",
            "scalar2",
            "scalar3",
            "scalar4",
            "constant",
        ),
    },
    "limited_memory_max_history": {"kind": "int", "low": 0.0, "low_inclusive": True},
    "limited_memory_max_skipping": {"kind": "int", "low": 1.0, "low_inclusive": True},
    "limited_memory_special_for_resto": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "limited_memory_update_type": {
        "kind": "str",
        "values": (
            "bfgs",
            "sr1",
        ),
    },
    "line_search_method": {
        "kind": "str",
        "values": (
            "filter",
            "cg-penalty",
            "penalty",
        ),
    },
    "linear_scaling_on_demand": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "linear_solver": {
        "kind": "str",
        "values": (
            "ma27",
            "ma57",
            "ma77",
            "ma86",
            "ma97",
            "pardiso",
            "pardisomkl",
            "spral",
            "wsmp",
            "mumps",
            "custom",
        ),
    },
    "linear_system_scaling": {
        "kind": "str",
        "values": (
            "none",
            "mc19",
            "slack-based",
        ),
    },
    "ma27_ignore_singularity": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "ma27_la_init_factor": {"kind": "float", "low": 1.0, "low_inclusive": True},
    "ma27_liw_init_factor": {"kind": "float", "low": 1.0, "low_inclusive": True},
    "ma27_meminc_factor": {"kind": "float", "low": 1.0, "low_inclusive": True},
    "ma27_pivtol": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 1.0,
        "high_inclusive": False,
    },
    "ma27_pivtolmax": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 1.0,
        "high_inclusive": False,
    },
    "ma27_print_level": {
        "kind": "int",
        "low": 0.0,
        "low_inclusive": True,
        "high": 4.0,
        "high_inclusive": True,
    },
    "ma27_skip_inertia_check": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "ma28_pivtol": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 1.0,
        "high_inclusive": True,
    },
    "ma57_automatic_scaling": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "ma57_block_size": {"kind": "int", "low": 1.0, "low_inclusive": True},
    "ma57_node_amalgamation": {"kind": "int", "low": 1.0, "low_inclusive": True},
    "ma57_pivot_order": {
        "kind": "int",
        "low": 0.0,
        "low_inclusive": True,
        "high": 5.0,
        "high_inclusive": True,
    },
    "ma57_pivtol": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 1.0,
        "high_inclusive": False,
    },
    "ma57_pivtolmax": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 1.0,
        "high_inclusive": False,
    },
    "ma57_pre_alloc": {"kind": "float", "low": 1.0, "low_inclusive": True},
    "ma57_print_level": {"kind": "int", "low": 0.0, "low_inclusive": True},
    "ma57_small_pivot_flag": {
        "kind": "int",
        "low": 0.0,
        "low_inclusive": True,
        "high": 1.0,
        "high_inclusive": True,
    },
    "ma77_buffer_lpage": {"kind": "int", "low": 1.0, "low_inclusive": True},
    "ma77_buffer_npage": {"kind": "int", "low": 1.0, "low_inclusive": True},
    "ma77_file_size": {"kind": "int", "low": 1.0, "low_inclusive": True},
    "ma77_maxstore": {"kind": "int", "low": 0.0, "low_inclusive": True},
    "ma77_nemin": {"kind": "int", "low": 1.0, "low_inclusive": True},
    "ma77_order": {
        "kind": "str",
        "values": (
            "amd",
            "metis",
        ),
    },
    "ma77_print_level": {"kind": "int"},
    "ma77_small": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "ma77_static": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "ma77_u": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": True,
        "high": 0.5,
        "high_inclusive": True,
    },
    "ma77_umax": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": True,
        "high": 0.5,
        "high_inclusive": True,
    },
    "ma86_nemin": {"kind": "int", "low": 1.0, "low_inclusive": True},
    "ma86_order": {
        "kind": "str",
        "values": (
            "auto",
            "amd",
            "metis",
        ),
    },
    "ma86_print_level": {"kind": "int"},
    "ma86_scaling": {
        "kind": "str",
        "values": (
            "none",
            "mc64",
            "mc77",
        ),
    },
    "ma86_small": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "ma86_static": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "ma86_u": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": True,
        "high": 0.5,
        "high_inclusive": True,
    },
    "ma86_umax": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": True,
        "high": 0.5,
        "high_inclusive": True,
    },
    "ma97_nemin": {"kind": "int", "low": 1.0, "low_inclusive": True},
    "ma97_order": {
        "kind": "str",
        "values": (
            "auto",
            "best",
            "amd",
            "metis",
            "matched-auto",
            "matched-metis",
            "matched-amd",
        ),
    },
    "ma97_print_level": {"kind": "int"},
    "ma97_scaling": {
        "kind": "str",
        "values": (
            "none",
            "mc30",
            "mc64",
            "mc77",
            "dynamic",
        ),
    },
    "ma97_scaling1": {
        "kind": "str",
        "values": (
            "none",
            "mc30",
            "mc64",
            "mc77",
        ),
    },
    "ma97_scaling2": {
        "kind": "str",
        "values": (
            "none",
            "mc30",
            "mc64",
            "mc77",
        ),
    },
    "ma97_scaling3": {
        "kind": "str",
        "values": (
            "none",
            "mc30",
            "mc64",
            "mc77",
        ),
    },
    "ma97_small": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "ma97_solve_blas3": {
        "kind": "str",
        "values": (
            "no",
            "yes",
        ),
    },
    "ma97_switch1": {
        "kind": "str",
        "values": (
            "never",
            "at_start",
            "at_start_reuse",
            "on_demand",
            "on_demand_reuse",
            "high_delay",
            "high_delay_reuse",
            "od_hd",
            "od_hd_reuse",
        ),
    },
    "ma97_switch2": {
        "kind": "str",
        "values": (
            "never",
            "at_start",
            "at_start_reuse",
            "on_demand",
            "on_demand_reuse",
            "high_delay",
            "high_delay_reuse",
            "od_hd",
            "od_hd_reuse",
        ),
    },
    "ma97_switch3": {
        "kind": "str",
        "values": (
            "never",
            "at_start",
            "at_start_reuse",
            "on_demand",
            "on_demand_reuse",
            "high_delay",
            "high_delay_reuse",
            "od_hd",
            "od_hd_reuse",
        ),
    },
    "ma97_u": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": True,
        "high": 0.5,
        "high_inclusive": True,
    },
    "ma97_umax": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": True,
        "high": 0.5,
        "high_inclusive": True,
    },
    "max_cpu_time": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "max_filter_resets": {"kind": "int", "low": 0.0, "low_inclusive": True},
    "max_hessian_perturbation": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "max_iter": {"kind": "int", "low": 0.0, "low_inclusive": True},
    "max_refinement_steps": {"kind": "int", "low": 0.0, "low_inclusive": True},
    "max_resto_iter": {"kind": "int", "low": 0.0, "low_inclusive": True},
    "max_soc": {"kind": "int", "low": 0.0, "low_inclusive": True},
    "max_soft_resto_iters": {"kind": "int", "low": 0.0, "low_inclusive": True},
    "max_wall_time": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "mehrotra_algorithm": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "min_hessian_perturbation": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "min_refinement_steps": {"kind": "int", "low": 0.0, "low_inclusive": True},
    "mu_allow_fast_monotone_decrease": {
        "kind": "str",
        "values": (
            "no",
            "yes",
        ),
    },
    "mu_init": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "mu_linear_decrease_factor": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 1.0,
        "high_inclusive": False,
    },
    "mu_max": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "mu_max_fact": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "mu_min": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "mu_oracle": {
        "kind": "str",
        "values": (
            "probing",
            "loqo",
            "quality-function",
        ),
    },
    "mu_strategy": {
        "kind": "str",
        "values": (
            "monotone",
            "adaptive",
        ),
    },
    "mu_superlinear_decrease_power": {
        "kind": "float",
        "low": 1.0,
        "low_inclusive": False,
        "high": 2.0,
        "high_inclusive": False,
    },
    "mu_target": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "mumps_dep_tol": {"kind": "float"},
    "mumps_mem_percent": {"kind": "int", "low": 0.0, "low_inclusive": True},
    "mumps_mpi_communicator": {"kind": "int"},
    "mumps_permuting_scaling": {
        "kind": "int",
        "low": 0.0,
        "low_inclusive": True,
        "high": 7.0,
        "high_inclusive": True,
    },
    "mumps_pivot_order": {
        "kind": "int",
        "low": 0.0,
        "low_inclusive": True,
        "high": 7.0,
        "high_inclusive": True,
    },
    "mumps_pivtol": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": True,
        "high": 1.0,
        "high_inclusive": True,
    },
    "mumps_pivtolmax": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": True,
        "high": 1.0,
        "high_inclusive": True,
    },
    "mumps_print_level": {"kind": "int", "low": 0.0, "low_inclusive": True},
    "mumps_scaling": {
        "kind": "int",
        "low": -2.0,
        "low_inclusive": True,
        "high": 77.0,
        "high_inclusive": True,
    },
    "neg_curv_test_reg": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "neg_curv_test_tol": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "nlp_lower_bound_inf": {"kind": "float"},
    "nlp_scaling_constr_target_gradient": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "nlp_scaling_max_gradient": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "nlp_scaling_method": {
        "kind": "str",
        "values": (
            "none",
            "user-scaling",
            "gradient-based",
            "equilibration-based",
        ),
    },
    "nlp_scaling_min_value": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "nlp_scaling_obj_target_gradient": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "nlp_upper_bound_inf": {"kind": "float"},
    "nu_inc": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "nu_init": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "num_linear_variables": {"kind": "int", "low": 0.0, "low_inclusive": True},
    "obj_max_inc": {"kind": "float", "low": 1.0, "low_inclusive": False},
    "obj_scaling_factor": {"kind": "float"},
    "option_file_name": {"kind": "str"},
    "output_file": {"kind": "str", "file_only": True},
    "pardiso_iter_coarse_size": {"kind": "int", "low": 1.0, "low_inclusive": True},
    "pardiso_iter_dropping_factor": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 1.0,
        "high_inclusive": False,
    },
    "pardiso_iter_dropping_schur": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 1.0,
        "high_inclusive": False,
    },
    "pardiso_iter_inverse_norm_factor": {"kind": "float", "low": 1.0, "low_inclusive": False},
    "pardiso_iter_max_levels": {"kind": "int", "low": 1.0, "low_inclusive": True},
    "pardiso_iter_max_row_fill": {"kind": "int", "low": 1.0, "low_inclusive": True},
    "pardiso_iter_relative_tol": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 1.0,
        "high_inclusive": False,
    },
    "pardiso_iterative": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "pardiso_matching_strategy": {
        "kind": "str",
        "values": (
            "complete",
            "complete+2x2",
            "constraints",
        ),
    },
    "pardiso_max_droptol_corrections": {"kind": "int", "low": 1.0, "low_inclusive": True},
    "pardiso_max_iter": {"kind": "int", "low": 1.0, "low_inclusive": True},
    "pardiso_max_iterative_refinement_steps": {"kind": "int"},
    "pardiso_msglvl": {"kind": "int", "low": 0.0, "low_inclusive": True},
    "pardiso_order": {
        "kind": "str",
        "values": (
            "amd",
            "metis",
            "pmetis",
        ),
    },
    "pardiso_redo_symbolic_fact_only_if_inertia_wrong": {
        "kind": "str",
        "values": (
            "no",
            "yes",
        ),
    },
    "pardiso_repeated_perturbation_means_singular": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "pardiso_skip_inertia_check": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "pardisolib": {"kind": "str"},
    "pardisomkl_matching_strategy": {
        "kind": "str",
        "values": (
            "complete",
            "complete+2x2",
            "constraints",
        ),
    },
    "pardisomkl_max_iterative_refinement_steps": {"kind": "int"},
    "pardisomkl_msglvl": {"kind": "int", "low": 0.0, "low_inclusive": True},
    "pardisomkl_order": {
        "kind": "str",
        "values": (
            "amd",
            "one",
            "metis",
            "pmetis",
        ),
    },
    "pardisomkl_redo_symbolic_fact_only_if_inertia_wrong": {
        "kind": "str",
        "values": (
            "no",
            "yes",
        ),
    },
    "pardisomkl_repeated_perturbation_means_singular": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "pardisomkl_skip_inertia_check": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "perturb_always_cd": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "perturb_dec_fact": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 1.0,
        "high_inclusive": False,
    },
    "perturb_inc_fact": {"kind": "float", "low": 1.0, "low_inclusive": False},
    "perturb_inc_fact_first": {"kind": "float", "low": 1.0, "low_inclusive": False},
    "point_perturbation_radius": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "print_advanced_options": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "print_frequency_iter": {"kind": "int", "low": 1.0, "low_inclusive": True},
    "print_frequency_time": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "print_info_string": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "print_level": {
        "kind": "int",
        "low": 0.0,
        "low_inclusive": True,
        "high": 12.0,
        "high_inclusive": True,
    },
    "print_options_documentation": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "print_options_mode": {
        "kind": "str",
        "values": (
            "text",
            "latex",
            "doxygen",
        ),
    },
    "print_timing_statistics": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "print_user_options": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "quality_function_balancing_term": {
        "kind": "str",
        "values": (
            "none",
            "cubic",
        ),
    },
    "quality_function_centrality": {
        "kind": "str",
        "values": (
            "none",
            "log",
            "reciprocal",
            "cubed-reciprocal",
        ),
    },
    "quality_function_max_section_steps": {"kind": "int", "low": 0.0, "low_inclusive": True},
    "quality_function_norm_type": {
        "kind": "str",
        "values": (
            "1-norm",
            "2-norm-squared",
            "max-norm",
            "2-norm",
        ),
    },
    "quality_function_section_qf_tol": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": True,
        "high": 1.0,
        "high_inclusive": False,
    },
    "quality_function_section_sigma_tol": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": True,
        "high": 1.0,
        "high_inclusive": False,
    },
    "recalc_y": {
        "kind": "str",
        "values": (
            "no",
            "yes",
        ),
    },
    "recalc_y_feas_tol": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "replace_bounds": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "required_infeasibility_reduction": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": True,
        "high": 1.0,
        "high_inclusive": False,
    },
    "residual_improvement_factor": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "residual_ratio_max": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "residual_ratio_singular": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "resto_failure_feasibility_threshold": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "resto_penalty_parameter": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "resto_proximity_weight": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "rho": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 1.0,
        "high_inclusive": False,
    },
    "s_max": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "s_phi": {"kind": "float", "low": 1.0, "low_inclusive": False},
    "s_theta": {"kind": "float", "low": 1.0, "low_inclusive": False},
    "sb": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "sigma_max": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "sigma_min": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "skip_corr_if_neg_curv": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "skip_corr_in_monotone_mode": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "skip_finalize_solution_call": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "slack_bound_frac": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 0.5,
        "high_inclusive": True,
    },
    "slack_bound_push": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "slack_move": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "soc_method": {
        "kind": "int",
        "low": 0.0,
        "low_inclusive": True,
        "high": 1.0,
        "high_inclusive": True,
    },
    "soft_resto_pderror_reduction_factor": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "spral_cpu_block_size": {"kind": "int", "low": 1.0, "low_inclusive": True},
    "spral_gpu_perf_coeff": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "spral_ignore_numa": {
        "kind": "str",
        "values": (
            "no",
            "yes",
        ),
    },
    "spral_max_load_inbalance": {"kind": "float", "low": 1.0, "low_inclusive": False},
    "spral_min_gpu_work": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "spral_nemin": {"kind": "int", "low": 1.0, "low_inclusive": True},
    "spral_order": {
        "kind": "str",
        "values": (
            "metis",
            "matching",
        ),
    },
    "spral_pivot_method": {
        "kind": "str",
        "values": (
            "aggressive",
            "block",
            "threshold",
        ),
    },
    "spral_print_level": {"kind": "int"},
    "spral_scaling": {
        "kind": "str",
        "values": (
            "none",
            "mc64",
            "auction",
            "matching",
            "ruiz",
            "dynamic",
        ),
    },
    "spral_scaling_1": {
        "kind": "str",
        "values": (
            "none",
            "mc64",
            "auction",
            "matching",
            "ruiz",
        ),
    },
    "spral_scaling_2": {
        "kind": "str",
        "values": (
            "none",
            "mc64",
            "auction",
            "matching",
            "ruiz",
        ),
    },
    "spral_scaling_3": {
        "kind": "str",
        "values": (
            "none",
            "mc64",
            "auction",
            "matching",
            "ruiz",
        ),
    },
    "spral_small": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "spral_small_subtree_threshold": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "spral_switch_1": {
        "kind": "str",
        "values": (
            "never",
            "at_start",
            "at_start_reuse",
            "on_demand",
            "on_demand_reuse",
            "high_delay",
            "high_delay_reuse",
            "od_hd",
            "od_hd_reuse",
        ),
    },
    "spral_switch_2": {
        "kind": "str",
        "values": (
            "never",
            "at_start",
            "at_start_reuse",
            "on_demand",
            "on_demand_reuse",
            "high_delay",
            "high_delay_reuse",
            "od_hd",
            "od_hd_reuse",
        ),
    },
    "spral_switch_3": {
        "kind": "str",
        "values": (
            "never",
            "at_start",
            "at_start_reuse",
            "on_demand",
            "on_demand_reuse",
            "high_delay",
            "high_delay_reuse",
            "od_hd",
            "od_hd_reuse",
        ),
    },
    "spral_u": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 0.5,
        "high_inclusive": True,
    },
    "spral_umax": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 0.5,
        "high_inclusive": True,
    },
    "spral_use_gpu": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "start_with_resto": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "tau_min": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 1.0,
        "high_inclusive": False,
    },
    "theta_max_fact": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "theta_min_fact": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "timing_statistics": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "tiny_step_tol": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "tiny_step_y_tol": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "tol": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "warm_start_bound_frac": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 0.5,
        "high_inclusive": True,
    },
    "warm_start_bound_push": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "warm_start_entire_iterate": {
        "kind": "str",
        "values": (
            "no",
            "yes",
        ),
    },
    "warm_start_init_point": {
        "kind": "str",
        "values": (
            "no",
            "yes",
        ),
    },
    "warm_start_mult_bound_push": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "warm_start_mult_init_max": {"kind": "float"},
    "warm_start_same_structure": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "warm_start_slack_bound_frac": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 0.5,
        "high_inclusive": True,
    },
    "warm_start_slack_bound_push": {"kind": "float", "low": 0.0, "low_inclusive": False},
    "warm_start_target_mu": {"kind": "float"},
    "watchdog_shortened_iter_trigger": {"kind": "int", "low": 0.0, "low_inclusive": True},
    "watchdog_trial_iter_max": {"kind": "int", "low": 1.0, "low_inclusive": True},
    "wsmp_inexact_droptol": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "wsmp_inexact_fillin_limit": {"kind": "float", "low": 0.0, "low_inclusive": True},
    "wsmp_max_iter": {"kind": "int", "low": 1.0, "low_inclusive": True},
    "wsmp_no_pivoting": {
        "kind": "str",
        "values": (
            "no",
            "yes",
        ),
    },
    "wsmp_num_threads": {"kind": "int"},
    "wsmp_ordering_option": {
        "kind": "int",
        "low": -2.0,
        "low_inclusive": True,
        "high": 3.0,
        "high_inclusive": True,
    },
    "wsmp_ordering_option2": {
        "kind": "int",
        "low": 0.0,
        "low_inclusive": True,
        "high": 3.0,
        "high_inclusive": True,
    },
    "wsmp_pivtol": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 1.0,
        "high_inclusive": False,
    },
    "wsmp_pivtolmax": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 1.0,
        "high_inclusive": False,
    },
    "wsmp_scaling": {
        "kind": "int",
        "low": 0.0,
        "low_inclusive": True,
        "high": 3.0,
        "high_inclusive": True,
    },
    "wsmp_singularity_threshold": {
        "kind": "float",
        "low": 0.0,
        "low_inclusive": False,
        "high": 1.0,
        "high_inclusive": False,
    },
    "wsmp_skip_inertia_check": {
        "kind": "str",
        "values": (
            "yes",
            "no",
        ),
    },
    "wsmp_write_matrix_iteration": {"kind": "int", "low": -1.0, "low_inclusive": True},
}
"""Documented kind, range, and allowed values of every Ipopt option."""
