version: 2

formats:
  - htmlzip

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
addons:
  apt:
    packages:
      - pandoc

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  builder: html
  configuration: "docs/user_guide/conf.py"
  fail_on_warning: true

