{% set name = "yass" %}
#{% set version = "0.1.0" %}
{% set version = environ.get('GIT_DESCRIBE_TAG').lstrip('v') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..
  # url: https://github.com/stevenrhall/simplejson/yapss/v{{ version }}.tar.gz
  # sha256: generate this with `openssl sha256 <filename>`

build:
  noarch: python
  number: 0

requirements:
  host:
    - python>=3.9,<3.14
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python>=3.9,<3.14
    - numpy
    - casadi>=3.6.0
    - scipy
    - mpmath
    - matplotlib
    - cyipopt

outputs:
  - name: yapss
    build:
      script: "{{ PYTHON }} -m pip install . --no-deps -vv"
    requirements:
      host:
        - python>=3.9,<3.14
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python>=3.9,<3.14
        - numpy
        - casadi>=3.6.0
        - scipy
        - mpmath
        - matplotlib
        - cyipopt
    test:
      source_files:
        - tests/examples/test_hs071.py
      requires:
        - pytest
      commands:
        - pytest tests/
    about:
      home: https://github.com/stevenrhall/yapss
      summary: "A Python package for solving optimal control problems using pseudospectral methods."
      description: |
        YAPSS is a Python package for numerically solving multi-phase optimal control problems using
        pseudospectral methods, similar to the GPOPS-II algorithm. The package supports multiple
        differentiation methods, including automatic differentiation using CasADi, as well as numerical
        derivatives found by central difference methods for problems that cannot be differentiated by
        automatic methods. YAPSS supports multiple collocation methods, including Legendre-Gauss (LG),
        Legendre-Gauss-Radau (LGR), and Legendre-Gauss-Lobatto (LGL) collocation points. The mesh
        structure can be specified by the user to improve the accuracy of the solution.
      license: MIT
      license_file: LICENSE
      doc_url: https://yapss.readthedocs.io
      dev_url: https://github.com/stevenrhall/yapss

  - name: yapss-dev
    build:
      script: "{{ PYTHON }} -m pip install .[dev] --no-deps -vv"
    requirements:
      host:
        - python>=3.9,<3.14
        - hatchling
        - hatch-vcs
        - pip
      run:
        # yapss dependencies
        - python>=3.9,<3.14
        - numpy
        - casadi>=3.6.0
        - scipy
        - mpmath
        - matplotlib
        - cyipopt
        # documentation
        - sphinx
        - sphinxcontrib-bibtex
        - sphinx-copybutton
        - sphinx_rtd_theme
        - myst-parser
        - nbsphinx
        - numpydoc
        - furo
        # notebooks
        - jupyterlab
        - jupyterlab_code_formatter
        - jupyterlab-spellchecker
        - ipython
        - black[jupyter]>=24.0.0,<25.0.0
        - isort
        - nbwipers
        # development
        - tox
        - pytest
        - pytest-cov
        - pytest-xdist
        - ruff
        - mypy
        - lxml
        - pyyaml
        - hatch
        - pre-commit
    test:
      source_files:
        - tests/examples/test_hs071.py
      requires:
        - pytest
      commands:
        - pytest tests/
    about:
      home: https://github.com/stevenrhall/yapss
      summary: "Development package for YAPSS, including documentation and testing tools."
      license: MIT
      license_file: LICENSE
      doc_url: https://yapss.readthedocs.io
      dev_url: https://github.com/stevenrhall/yapss

extra:
  recipe-maintainers:
    - stevenrhall