"""Render the error catalogue for the development documentation.

Every message YAPSS raises for a user mistake is stated by a clause of the contract suite,
through `tests/contract/_harness.py::raises`. That helper appends what it saw to a file
when ``YAPSS_ERROR_CATALOG`` is set, and this script renders those records as one page.

The catalogue is therefore generated, never written by hand, and cannot describe a message
the code does not actually produce. Its completeness is exactly the contract suite's: an
error missing from the page is an error no clause covers, which is worth knowing.

Usage (or ``make error-catalog``)::

    YAPSS_ERROR_CATALOG=build/errors.jsonl pytest tests/contract -q
    python tools/error_catalog.py build/errors.jsonl
"""

from __future__ import annotations

import argparse
import json
import re
import textwrap
from collections import defaultdict
from pathlib import Path

PAGE = Path("docs/development/source/error_catalog.rst")

AREAS = {
    "problem": "Problem construction and configuration",
    "bounds": "Bounds",
    "guess": "Guess",
    "scale": "Scale",
    "callbacks": "Callbacks and user derivatives",
    "solve": "Solving and Ipopt options",
    "solution": "Solution",
    "protection": "Attribute protection",
    "warnings": "Warnings",
}

# The 0.4.0 suite's areas are the reference pages, in the reference's own order, so that a
# reader meets the messages in the order the reference introduces their subjects -- and so
# that a page with no messages is visible as a gap rather than as an absence.
API_AREAS = {
    "problem": "Problem Definition",
    "callbacks": "Callback Functions",
    "bounds": "Bounds",
    "guess": "Initial Guess",
    "derivatives": "Derivatives",
    "scaling": "Scaling",
    "mesh_structure": "Mesh Structure",
    "ipopt_options": "Ipopt Options",
    "solution": "Solution",
    "warnings": "Warnings",
    "protection": "Names and Attributes",
}

# Messages that differ only in the value they echo are one entry with one example.
_VALUE = re.compile(
    r"array\(\[[^]]*\]\)|<[^>]+>|'[^']*'|\"[^\"]*\"|-?\d+\.\d+e[-+]\d+|-?\d+\.?\d*",
)

# Test scaffolding rather than something a user would write: parametrized tests reach the
# attribute through setattr/getattr/exec, which would be noise in a sample traceback.
_SCAFFOLD = re.compile(r"\b(setattr|getattr|delattr|exec|owner|form|pytest|raises)\s*\(")
_COMMENT = re.compile(r"\s+#\s*(type:\s*ignore|noqa)\b.*$")


def shape(message: str) -> str:
    """Return the message with the values it echoes replaced, for grouping."""
    return _VALUE.sub("*", message)


def as_user_wrote_it(statement: str) -> str:
    """Return the statement if it reads like user code, else "".

    The catalogue shows a sample traceback, and the line in it should look like something a
    reader might have written. A parametrized test's `setattr(...)` call, a bare `).solve()`
    continuation, or a `# type: ignore` comment would all be noise.
    """
    text = _COMMENT.sub("", statement).strip()
    if not text or text.startswith(")") or _SCAFFOLD.search(text):
        return ""
    return text


def render(records: list[dict[str, str]], *, front: str = "legacy") -> str:
    """Return the reStructuredText page for the harvested records.

    `front` selects the section order and the voice: the development page lists the areas of
    the 0.3.0 suite and names the clause that states each message, and the user page lists the
    reference's own pages in the reference's order.
    """
    areas = API_AREAS if front == "api" else AREAS
    name_the_clause = front != "api"
    grouped: dict[str, dict[str, dict[str, list[dict[str, str]]]]] = defaultdict(
        lambda: defaultdict(lambda: defaultdict(list)),
    )
    for record in records:
        grouped[record["area"]][record["type"]][shape(record["message"])].append(record)

    total = sum(len(by_shape) for by_type in grouped.values() for by_shape in by_type.values())
    raw = len(records)
    if front == "api":
        lines = [
            "What YAPSS Will Tell You",
            "========================",
            "",
            ".. This page is generated by tools/error_catalog.py. Do not edit it by hand.",
            "",
            "Every message YAPSS raises or warns about, in the order of the reference. Each was",
            "produced by running YAPSS rather than transcribed, so nothing here describes a",
            f"message the code does not produce. {total} distinct messages, from {raw} occasions",
            "of being told something.",
            "",
            "Messages that differ only in the value they echo are shown once, with one example",
            "and a count. A message reaches you as the last line of a traceback, which is how it",
            "is shown here, with the statement that provoked it above.",
            "",
            "The page is as complete as the contract suite, which states each message as a",
            "clause: a message missing here is one no clause covers.",
            "",
        ]
    else:
        lines = [
            "Error Catalogue",
            "===============",
            "",
            ".. This page is generated by tools/error_catalog.py. Do not edit it by hand.",
            "",
            "Every message below was produced by running YAPSS, not transcribed. It is harvested",
            "from the contract suite, which states each message as a clause, so the page cannot",
            f"describe a message the code does not produce. {total} distinct messages,",
            f"{raw} before collapsing those that differ only in the value they echo.",
            "Rerun with ``make error-catalog``.",
            "",
            "Messages differing only in the value they echo are shown once, with one example and",
            "a count. The page is as complete as the contract suite: an error that does not",
            "appear here has no clause covering it.",
            "",
        ]

    def show(entries: list[dict[str, str]]) -> None:
        """Append one message, as the traceback a user meets it in."""
        first = entries[0]
        # shown as it reaches the user: a traceback ending in the message, which is
        # also what makes Pygments colour the exception name as a terminal would
        lines.extend([".. code-block:: pytb", ""])
        lines.extend(["   Traceback (most recent call last):", "     ..."])
        statement = as_user_wrote_it(first["statement"])
        if statement:
            lines.append("       " + statement)
        body = f"{first['type']}: {first['message']}"
        for i, line in enumerate(body.split("\n")):
            wrapped = textwrap.wrap(line, 86) or [""]
            indent = "   " if i == 0 else "       "
            lines.append(indent + wrapped[0])
            lines.extend("       " + part for part in wrapped[1:])
        lines.append("")
        more = f", and {len(entries) - 1} more like it" if len(entries) > 1 else ""
        if name_the_clause:
            lines.extend([f"Stated by ``{first['test']}``{more}.", ""])
        elif more:
            lines.extend([f"There are {len(entries)} messages of this shape.", ""])

    for area in [a for a in areas if a in grouped] + sorted(set(grouped) - set(areas)):
        title = areas.get(area, area.replace("_", " ").title())
        lines.extend([title, "-" * len(title), ""])
        if name_the_clause:
            # the development page keeps the exception type as a heading, which is how it is
            # read there: by someone asking what a given class of failure looks like
            for exc in sorted(grouped[area]):
                lines.extend([exc, "~" * len(exc), ""])
                for _, entries in sorted(
                    grouped[area][exc].items(), key=lambda kv: kv[1][0]["message"]
                ):
                    show(entries)
            continue
        # The user page has no such heading. Which exception class a message carries is a
        # fact about Python, not about the subject, and heading by it separates messages a
        # reader wants side by side. The class is still there, in the traceback's last line,
        # which is where a reader meets it anyway.
        by_message = [
            entries
            for by_shape in [grouped[area][exc] for exc in sorted(grouped[area])]
            for entries in by_shape.values()
        ]
        for entries in sorted(by_message, key=lambda e: e[0]["message"]):
            show(entries)
    return "\n".join(lines) + "\n"


def main(path: str, out: Path = PAGE, front: str = "legacy") -> int:
    """Read the harvested records of one front end and write its page."""
    source = Path(path)
    if not source.exists():
        print(f"no records at {source}; run the contract suite with YAPSS_ERROR_CATALOG set")
        return 1
    seen: set[tuple[str, str, str]] = set()
    records = []
    for line in source.read_text(encoding="utf-8").splitlines():
        record = json.loads(line)
        # records written before the front end was recorded are the 0.3.0 suite's
        if record.get("front", "legacy") != front:
            continue
        key = (record["area"], record["type"], record["message"])
        if key not in seen:
            seen.add(key)
            records.append(record)
    if not records:
        print(f"no {front} records in {source}")
        return 1
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(records, front=front), encoding="utf-8")
    print(f"{len(records)} distinct {front} messages -> {out}")
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("records", nargs="?", default="build/errors.jsonl")
    parser.add_argument("--out", type=Path, default=None, help="the page to write")
    parser.add_argument("--front", default="legacy", choices=("legacy", "api"))
    args = parser.parse_args()
    raise SystemExit(main(args.records, args.out or PAGE, args.front))
