"""Render the error catalogue for the development documentation.

Every message YAPSS raises for a user mistake is stated by a clause of the contract suite,
through `tests/contract/_contract.py::raises`. That helper appends what it saw to a file
when ``YAPSS_ERROR_CATALOG`` is set, and this script renders those records as one page.

The catalogue is therefore generated, never written by hand, and cannot describe a message
the code does not actually produce. Its completeness is exactly the contract suite's: an
error missing from the page is an error no clause covers, which is worth knowing.

Usage (or ``make error-catalog``)::

    YAPSS_ERROR_CATALOG=build/errors.jsonl pytest tests/contract -q
    python tools/error_catalog.py build/errors.jsonl
"""

from __future__ import annotations

import json
import re
import sys
import textwrap
from collections import defaultdict
from pathlib import Path

PAGE = Path("docs/development/source/error_catalog.rst")

AREAS = {
    "problem": "Problem construction and configuration",
    "bounds": "Bounds",
    "guess": "Guess",
    "scale": "Scale",
    "callbacks": "Callbacks and user derivatives",
    "solve": "Solving and Ipopt options",
    "solution": "Solution",
    "protection": "Attribute protection",
    "warnings": "Warnings",
}

# Messages that differ only in the value they echo are one entry with one example.
_VALUE = re.compile(
    r"array\(\[[^]]*\]\)|<[^>]+>|'[^']*'|\"[^\"]*\"|-?\d+\.\d+e[-+]\d+|-?\d+\.?\d*",
)

# Test scaffolding rather than something a user would write: parametrized tests reach the
# attribute through setattr/getattr/exec, which would be noise in a sample traceback.
_SCAFFOLD = re.compile(r"\b(setattr|getattr|delattr|exec|owner|form|pytest|raises)\s*\(")
_COMMENT = re.compile(r"\s+#\s*(type:\s*ignore|noqa)\b.*$")


def shape(message: str) -> str:
    """Return the message with the values it echoes replaced, for grouping."""
    return _VALUE.sub("*", message)


def as_user_wrote_it(statement: str) -> str:
    """Return the statement if it reads like user code, else "".

    The catalogue shows a sample traceback, and the line in it should look like something a
    reader might have written. A parametrized test's `setattr(...)` call, a bare `).solve()`
    continuation, or a `# type: ignore` comment would all be noise.
    """
    text = _COMMENT.sub("", statement).strip()
    if not text or text.startswith(")") or _SCAFFOLD.search(text):
        return ""
    return text


def render(records: list[dict[str, str]]) -> str:
    """Return the reStructuredText page for the harvested records."""
    grouped: dict[str, dict[str, dict[str, list[dict[str, str]]]]] = defaultdict(
        lambda: defaultdict(lambda: defaultdict(list)),
    )
    for record in records:
        grouped[record["area"]][record["type"]][shape(record["message"])].append(record)

    total = sum(len(by_shape) for by_type in grouped.values() for by_shape in by_type.values())
    raw = len(records)
    lines = [
        "Error Catalogue",
        "===============",
        "",
        ".. This page is generated by tools/error_catalog.py. Do not edit it by hand.",
        "",
        "Every message below was produced by running YAPSS, not transcribed. It is harvested",
        "from the contract suite, which states each message as a clause, so the page cannot",
        f"describe a message the code does not produce. {total} distinct messages ({raw} before",
        "collapsing those that differ only in the value they echo). Rerun with",
        "``make error-catalog``.",
        "",
        "Messages differing only in the value they echo are shown once, with one example and a",
        "count. The page is as complete as the contract suite: an error that does not appear",
        "here has no clause covering it.",
        "",
    ]

    for area in [a for a in AREAS if a in grouped] + sorted(set(grouped) - set(AREAS)):
        lines += [AREAS.get(area, area.title()), "-" * len(AREAS.get(area, area.title())), ""]
        for exc in sorted(grouped[area]):
            lines += [exc, "~" * len(exc), ""]
            for _, entries in sorted(
                grouped[area][exc].items(), key=lambda kv: kv[1][0]["message"]
            ):
                first = entries[0]
                # shown as it reaches the user: a traceback ending in the message, which is
                # also what makes Pygments colour the exception name as a terminal would
                lines += [".. code-block:: pytb", ""]
                lines += ["   Traceback (most recent call last):", "     ..."]
                statement = as_user_wrote_it(first["statement"])
                if statement:
                    lines += ["       " + statement]
                body = f"{first['type']}: {first['message']}"
                for i, line in enumerate(body.split("\n")):
                    wrapped = textwrap.wrap(line, 86) or [""]
                    indent = "   " if i == 0 else "       "
                    lines += [indent + wrapped[0]]
                    lines += ["       " + part for part in wrapped[1:]]
                lines += [""]
                more = f", and {len(entries) - 1} more like it" if len(entries) > 1 else ""
                lines += [f"Stated by ``{first['test']}``{more}.", ""]
    return "\n".join(lines) + "\n"


def main(path: str) -> int:
    """Read the harvested records and write the page."""
    source = Path(path)
    if not source.exists():
        print(f"no records at {source}; run the contract suite with YAPSS_ERROR_CATALOG set")
        return 1
    seen: set[tuple[str, str, str]] = set()
    records = []
    for line in source.read_text(encoding="utf-8").splitlines():
        record = json.loads(line)
        key = (record["area"], record["type"], record["message"])
        if key not in seen:
            seen.add(key)
            records.append(record)
    PAGE.write_text(render(records), encoding="utf-8")
    print(f"{len(records)} distinct messages -> {PAGE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1] if len(sys.argv) > 1 else "build/errors.jsonl"))
